# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: checkin.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcheckin.proto\x12\x07\x63heckin\"2\n\rTicketRequest\x12\x10\n\x08ticketId\x18\x01 \x01(\t\x12\x0f\n\x07\x65ventId\x18\x02 \x01(\t\"-\n\x0bTicketReply\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2O\n\rTicketService\x12>\n\x0eValidateTicket\x12\x16.checkin.TicketRequest\x1a\x14.checkin.TicketReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checkin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKETREQUEST']._serialized_start=26
  _globals['_TICKETREQUEST']._serialized_end=76
  _globals['_TICKETREPLY']._serialized_start=78
  _globals['_TICKETREPLY']._serialized_end=123
  _globals['_TICKETSERVICE']._serialized_start=125
  _globals['_TICKETSERVICE']._serialized_end=204
# @@protoc_insertion_point(module_scope)
